version: "3.9"

services:
  aiogames:
    build: .
    container_name: aiogames
    ports:
      - "${PORT:-2000}:2000"  # Frontend/Backend API only
    volumes:
      - ./data:/app/data              # Application data
      - ./downloads:/app/downloads     # Download directory
      - ./config:/app/config          # Config files
      - ./.env:/app/.env             # Environment variables
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - MONGODB_URI=mongodb://mongodb:27017/aiogames
      - ARIA2_HOST=localhost
      - ARIA2_PORT=6800
      - ARIA2_SECRET=${ARIA2_SECRET:-changeme}
      - QBITTORRENT_URL=http://localhost:8080
      - QBITTORRENT_USERNAME=${QB_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QB_PASSWORD:-adminadmin}
      - JDOWNLOADER_EMAIL=${JD_EMAIL}
      - JDOWNLOADER_PASSWORD=${JD_PASSWORD}
      - STEAM_API_KEY=${STEAM_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:2000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: aiogames-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb_data: