version: '3.8'

services:
  # Main Application
  aiogames:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - MONGODB_URI=${MONGODB_URI}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - GAME_API_URL=${GAME_API_URL}
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MONGODB_URI=mongodb://aiogames:aiogames123@aiogames-mongodb-dev:27017/aiogames
      - GAME_API_URL=${GAME_API_URL}
    env_file: .env
    restart: unless-stopped
    networks:
      - aiogames-dev-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: MongoDB (if not using Atlas)
  # mongodb:
  #   image: mongo:7
  #   container_name: aiogames-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #     - MONGO_INITDB_DATABASE=aiogames
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped

  # Optional: MongoDB Web Interface
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin
  #   depends_on:
  #     - mongodb

# volumes:
#   mongodb_data:

networks:
  aiogames-dev-network:
    external: true